### ISSUE TITLE
Error when i open the project

### ISSUE THREAD

**Issue by pooyapower** [kreaninw/G4-Ultimate-Touch-Joypad#1]
hi
thanks for your work.
i downloaded your project and when i open it 2 errors come up.
can you fix them ?
![01](https://user-images.githubusercontent.com/36620298/214684646-33713eb1-9193-4a7c-aa14-d02ed140098a.png)
![02](https://user-images.githubusercontent.com/36620298/214684653-f3017503-741c-491e-a73e-6e42fc1e9888.png)

**Comment by archerallstars** [comment]
Hi, Godot 4 dropped Visual Script support since beta. That could be the reason why the errors occur.

Thanks for your interest ❤️

**Comment by RpixPro** [comment]
Please change it to gdscript
